apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Release.Name }}-explorer
rules:
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name }}-explorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $.Release.Name }}-explorer
subjects:
- kind: ServiceAccount
  name: {{ $.Release.Name }}-explorer
  namespace: {{ $.Release.Namespace }}

