apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-explorer
  labels:
    {{- include "pod-explorer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
