name: Sync DSO

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Curl DSO APi
        run: |
          curl --location --request POST 'https://${{ secrets.DSO_GRAVITEE_HOST }}/gitlab-dso/${{ vars.DSO_MIRROR_ID }}/trigger/pipeline'\
            --header 'X-Gravitee-Api-Key: ${{ secrets.GRAVITEE_TOKEN }}'\
            --form 'token=${{ secrets.GITLAB_TOKEN }}'\
            --form 'ref="main"'\
            --form 'variables[PROJECT_NAME]="${{ vars.DSO_PROJECT_NAME }}"'\
            --form 'variables[BRANCH_NAME]="${{ github.ref_name }}'
